spring:
  datasource: 
    url: jdbc:mysql://175.178.238.125:13306/the_four_seasons_of_books?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: jgh
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
  mvc: 
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  file:
    name: log/app.log
  level:
    root: info
    org.springframework: warn
