server:
  port: 8080
  servlet:
    context-path:
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_book_manager?useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://175.178.238.125:13306/the_four_seasons_of_books?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
  mvc: 
    pathmatch:
      matching-strategy: ant-path-matcher
  banner:
    charset: utf-8
    image:
      location: banner.txt
logging:
  file:
    name: log/app.log
  level:
    root: info
    org.springframework: warn
